/**
 * Centralized Icon Exports
 *
 * This file serves as the single source of truth for all lucide-react icons used
 * throughout the application. By consolidating imports here, we enable:
 *
 * 1. Better tracking of which icons are actually used
 * 2. Potential code-splitting opportunities
 * 3. Easier future migration to alternative icon solutions
 * 4. Reduced bundle size through optimized tree-shaking
 *
 * Usage:
 *   import { AlertCircle, Check, X } from '@/lib/icons';
 *
 * When adding new icons:
 *   1. Import the icon from 'lucide-react'
 *   2. Add it to the export statement in alphabetical order
 */

export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Box,
  Brain,
  Bug,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  CloudDownload,
  Code,
  Code2,
  Cog,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileDown,
  FileImage,
  FileJson,
  FileText,
  Filter,
  FlaskConical,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  FolderTree,
  FolderX,
  Gauge,
  GitBranch,
  GitCommit,
  Github,
  GitMerge,
  Globe,
  Grid2X2,
  HardDrive,
  HelpCircle,
  History,
  Image,
  Import,
  Inbox,
  Info,
  Key,
  KeyRound,
  Layers,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  ListTodo,
  Loader2,
  Lock,
  LogIn,
  Mail,
  Map,
  MessageCircle,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  Package,
  Palette,
  PanelLeft,
  PanelLeftClose,
  PartyPopper,
  Pencil,
  PenLine,
  Play,
  Plus,
  Radio,
  RefreshCw,
  Rocket,
  RotateCcw,
  Route,
  Save,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Shield,
  Sliders,
  Sparkles,
  Square,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  TerminalSquare,
  ThumbsUp,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  Wand2,
  Wifi,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

// Re-export Image as ImageIcon for components that use this alias
export { Image as ImageIcon } from 'lucide-react';
