name: 📚 Documentation
description: Improvements or additions to documentation
labels: ["documentation", "needs-triage", "help wanted"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Missing documentation
        - Incorrect/outdated info
        - Improvement suggestion
        - Typo/grammar fix
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Which file or page?
      placeholder: "e.g., README.md or guides/setup.md"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to change?
    validations:
      required: true

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR for this
